services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACK_PORT:-5000}:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "${REACT_APP_FRONT_PORT:-3000}:3000"
    env_file:
      - ./frontend/.env